# Generated by Django 5.1.6 on 2025-07-21 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_index', '0005_category_label_alter_category_code_and_more'),
        ('app_main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_index.category', verbose_name='Catégorie liée'),
        ),
    ]
