# Generated by Django 5.1.6 on 2025-07-25 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0002_tag_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadablefile',
            name='subtitle',
            field=models.CharField(blank=True, help_text='Sous-titre optionnel affiché sous le titre principal.', max_length=255),
        ),
        migrations.AlterField(
            model_name='staticpagemeta',
            name='category',
            field=models.CharField(choices=[('site-info', 'Pages de base'), ('aide', 'Pages Aide/FAQ')], default='custom', help_text='Permet de trier les pages selon leur usage', max_length=20, verbose_name='Catégorie'),
        ),
    ]
