# Generated by Django 5.1.6 on 2025-07-25 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0003_downloadablefile_subtitle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadablefile',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Nom du fichier'),
        ),
        migrations.AlterUniqueTogether(
            name='downloadablefile',
            unique_together={('title', 'subtitle')},
        ),
    ]
