# Generated by Django 5.1.6 on 2025-05-03 15:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Nom court de la catégorie, affiché dans les formulaires et les listes.', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text="Description de la catégorie : explique ce qu'elle regroupe. Affichée dans l'admin pour aider à faire le bon choix.")),
                ('slug', models.SlugField(blank=True, help_text='Slug généré automatiquement à partir du nom si laissé vide.', max_length=100, unique=True)),
            ],
            options={
                'verbose_name': "Catégorie d'article",
                'verbose_name_plural': "Catégories d'article",
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(help_text="Titre de l'article (affiché dans la liste et sur la page).", max_length=200)),
                ('slug', models.SlugField(blank=True, help_text='Généré automatiquement à partir du titre si vide.', max_length=200, unique=True)),
                ('resume', models.TextField(blank=True, help_text="Résumé de l'article. S'affiche dans les aperçus. Si vide, un extrait automatique sera utilisé.")),
                ('contenu', models.TextField(help_text='Contenu principal de l’article (avec mise en forme TinyMCE).')),
                ('image', models.ImageField(blank=True, help_text="Image d'illustration de l'article. Elle sera automatiquement redimensionnée à une largeur maximale de 1200 px et compressée (qualité 85 %). Préférez une image d’au moins 1200 px de large.Une image plus petite ne sera pas redimensionnée.", null=True, upload_to='blog/illustrations/')),
                ('date_publication', models.DateTimeField(db_index=True, help_text='Date initiale de publication.', null=True)),
                ('date_modification', models.DateTimeField(auto_now=True, help_text='Date de dernière modification.')),
                ('est_publie', models.BooleanField(default=False, help_text="L'article est-il visible publiquement ?")),
                ('auteur', models.ForeignKey(help_text="Utilisateur ayant rédigé l'article.", null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, help_text='Tags associés à cet article (navigation par thème).', related_name='articles', to='app_main.tag')),
                ('categorie_principale', models.ForeignKey(help_text='Catégorie principale de l’article.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='articles_avec_cette_categorie_principale', to='app_blog.categoriearticle')),
                ('categories_secondaires', models.ManyToManyField(blank=True, help_text='Catégories secondaires (optionnelles).', related_name='articles_avec_cette_categorie_secondaire', to='app_blog.categoriearticle')),
            ],
            options={
                'verbose_name': 'Article de blog',
                'verbose_name_plural': 'Articles de blog',
                'ordering': ['-date_publication'],
                'get_latest_by': 'date_publication',
            },
        ),
    ]
