# Generated by Django 5.1.6 on 2025-07-30 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'get_latest_by': 'date_publication', 'ordering': ['-date_publication'], 'verbose_name': 'Article de blog', 'verbose_name_plural': 'Blog - Articles'},
        ),
        migrations.AlterModelOptions(
            name='categoriearticle',
            options={'ordering': ['nom'], 'verbose_name': "Catégorie d'article", 'verbose_name_plural': "Blog - Catégories d'articles"},
        ),
        migrations.AddField(
            model_name='article',
            name='masquer_image',
            field=models.BooleanField(default=False, help_text="Cochez pour masquer l'image d'illustration en haut de l'article (elle reste utilisée pour la liste d'articles).", verbose_name="Ne pas afficher l'image d'illustration dans l'article"),
        ),
    ]
