# Generated by Django 5.1.6 on 2025-08-05 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0002_alter_article_options_alter_categoriearticle_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='last_viewed',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de dernière vue'),
        ),
        migrations.AddField(
            model_name='article',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='Nombre de vues'),
        ),
    ]
