# Generated by Django 5.1.6 on 2025-07-20 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_index', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Catégorie', 'verbose_name_plural': 'Index - Catégories'},
        ),
        migrations.AlterModelOptions(
            name='pagetype',
            options={'ordering': ['label'], 'verbose_name': 'Type de page', 'verbose_name_plural': 'Index - Types de pages'},
        ),
        migrations.RemoveField(
            model_name='pagetype',
            name='name',
        ),
        migrations.AddField(
            model_name='pagetype',
            name='code',
            field=models.CharField(default='temp', help_text='Identifiant technique, utilisé dans le code (ex: artiste_biography, label_history).', max_length=50, unique=True, verbose_name='Code technique'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pagetype',
            name='label',
            field=models.CharField(default='temp', help_text='Nom affiché du type de page (ex: Biographie (Artistes)).', max_length=100, verbose_name='Nom affiché'),
            preserve_default=False,
        ),
    ]
