# Generated by Django 5.1.6 on 2025-07-20 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_index', '0004_alter_category_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='label',
            field=models.CharField(default='temp', max_length=100, verbose_name='Libellé affiché (au pluriel, si besoin)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='code',
            field=models.CharField(default='temp', help_text='Clé technique unique (ex: artiste, compilation, label, lexique, etc.).', max_length=50, unique=True, verbose_name='Code'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='indexsettings',
            unique_together={('category',)},
        ),
    ]
