# Generated by Django 5.1.6 on 2025-07-25 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_index', '0005_category_label_alter_category_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexentry',
            name='name',
            field=models.CharField(help_text="Nom officiel de l'entrée (ex: Michael Jackson, Top DJ Hits)", max_length=255, verbose_name='Nom'),
        ),
        migrations.AlterUniqueTogether(
            name='indexentry',
            unique_together={('name', 'category')},
        ),
    ]
