# Generated by Django 5.1.6 on 2025-07-25 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_index', '0006_alter_indexentry_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='indexentry',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='indexentry',
            name='name',
            field=models.CharField(help_text="Nom officiel de l'entrée (ex: Michael Jackson, Top DJ Hits)", max_length=255, unique=True, verbose_name='Nom'),
        ),
    ]
