# Generated by Django 5.1.6 on 2025-08-16 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_index', '0007_alter_indexentry_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(help_text="Variation du nom (ex. : '2Unlimited', 'Mylene Farmer', 'Daft punk', 'Jackson, Michael').", max_length=255, verbose_name='Alias')),
                ('alias_normalized', models.CharField(db_index=True, editable=False, help_text='Généré automatiquement : sans accents/ponctuation, en minuscules, espaces compactés.', max_length=255, verbose_name='Alias normalisé')),
                ('category', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='app_index.category', verbose_name='Catégorie (copie)')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='app_index.indexentry', verbose_name='Entrée principale')),
            ],
            options={
                'verbose_name': "Alias d'index",
                'verbose_name_plural': 'Index - Alias',
                'ordering': ['alias'],
                'indexes': [models.Index(fields=['category', 'alias_normalized'], name='app_index_i_categor_2b0e2d_idx'), models.Index(fields=['entry'], name='app_index_i_entry_i_56df70_idx')],
                'constraints': [models.UniqueConstraint(fields=('category', 'alias_normalized'), name='uniq_alias_normalized_per_category')],
            },
        ),
    ]
