# Generated by Django 5.1.6 on 2025-08-16 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_index', '0009_fix_indexalias_fk_mysql'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexalias',
            name='is_listed',
            field=models.BooleanField(default=True, help_text='Si décoché, l’alias reste pris en compte pour la recherche et pointe vers les mêmes liens que l’entrée principale, mais il n’est pas listé dans l’index.', verbose_name='Afficher dans l’index'),
        ),
    ]
